[package]
name = "multistack"
version = "1.0.0-rc6"
edition = "2024"
authors = ["Giuseppe Della Vedova"]
description = "Open source lightweight TUI for parallel agent management"
license = "GPL-3.0-only"
homepage = "https://github.com/gi-dellav/multistack"
repository = "https://github.com/gi-dellav/multistack"
readme = "README.md"
keywords = ["ai", "cli", "tui", "dev"]

[dependencies]
crossterm = { version = "0.29.0", features = ["event-stream"] }
futures = "0.3"
notify-rust = "4.17.0"
parking_lot = "0.12.5"
portable-pty = "0.9.0"
ratatui = { version = "0.30", features = ["crossterm"] }
ratatui-explorer = { git = "https://github.com/gi-dellav/ratatui-explorer.git", version = "0.3.0" }

tokio = { version = "1", features = ["full"] }
vt100 = "0.16.2"
